import { test, expect } from "@playwright/test";
import HomePage from "../page-objects/HomePage";
import CartPage from "../page-objects/CartPage"

// It wasn't specified that it has to be done through the products page, therefor did this through base page
test.describe.skip("Add to cart tests", async () => {
test("Add item to cart and assert that the correct item with the correct price is shown in the cart", async ({ page }) => {
    const homePage = new HomePage(page);
    const cartPage = new CartPage(page);
    
    await homePage.navigateToPage("/");
    await homePage.addBlueTopToCart();
    await homePage.clickViewCartHyperlink();
    await cartPage.assertItemIsVisibleInCart("Blue Top","Women > Tops", "Rs. 500");
  });

test('Add item to cart and assert that the correct item with the correct price is shown in the cart - generated by codegen', async ({ page }) => {
    await page.goto('https://automationexercise.com/');
    await page.locator('.productinfo > .btn').first().click();
    await page.getByRole('link', { name: 'View Cart' }).click();
    await expect(page.locator('#product-1')).toContainText('Blue Top');
    await expect(page.locator('#product-1')).toContainText('Women > Tops');
    await expect(page.locator('#product-1')).toContainText('Rs. 500');
  });
});
  